### ISSUE TITLE
Running the client and server

### ISSUE THREAD

**Issue by ValentinaChaconBuitrago** [jeremyfix/udp_video_streaming#1]
Hi Jeremy! Thank you for your implementation, I want to try your UDP approach but unfortunately I haven't been able to do it. I did what you said in your read.me but i'm new to this and I don't know if i'm doing it right. Could you please help me?
Thank you :) 
![Captura de pantalla 2019-03-22 a la(s) 3 15 08 p  m](https://user-images.githubusercontent.com/35730663/54850512-588df280-4cb5-11e9-96da-29c572feaaac.png)

**Comment by jeremyfix** [comment]
Can you provide the output of the command

   ifconfig

jeremy.

**Comment by ValentinaChaconBuitrago** [comment]
Hi Jeremy
This is what appears
![Captura de pantalla 2019-03-22 a la(s) 3 37 40 p  m](https://user-images.githubusercontent.com/35730663/54851599-7c066c80-4cb8-11e9-81ba-543333bdd658.png)

**Comment by jeremyfix** [comment]
In one terminal, you run

python3 serverUDPB.py en0

In another one, you can run the client

python3 client.py 157.253.218.48 1080

That should make it.

**Comment by ValentinaChaconBuitrago** [comment]
Thanks! And where should I put the get command?
The window image appears but the video is not appearing
![Captura de pantalla 2019-03-22 a la(s) 3 50 47 p  m](https://user-images.githubusercontent.com/35730663/54852268-65f9ab80-4cba-11e9-8655-1ce44a1006ee.png)

**Comment by ValentinaChaconBuitrago** [comment]
It got it to work by changing the ip to 127.0.0.1 and the port to 20001. You are great Jeremy, thank you so much for your help!! :)
